# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Install runtime dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.9.2 httpx>=0.28.1

# Copy application code
COPY . .

# Entry point
ENTRYPOINT ["python", "cp_traintracking.py"]
