# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim
WORKDIR /app
# Copy all files
COPY . .
# Install dependencies and fix code syntax
RUN pip install --no-cache-dir mcp httpx rapidfuzz && \
    sed -i 's/score_cutoff=70 /score_cutoff=70)/' cp_traintracking.py

# Expose optional PORT env var usage (stdio doesn't need port)
ENV PYTHONUNBUFFERED=1

CMD ["python", "cp_traintracking.py"]
